# docker-compose.yml
version: "3.9"
services:
  db:
    image: postgres:17-alpine
    ports:
      - "5544:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-bookshop}
      TZ: Asia/Kolkata
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  pgdata:
