package com.govind.bookshop.author.domain.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity representing the {@code authors} table.
 *
 * <p>This model is internal to the persistence layer and should not leak to
 * API consumers. Use {@link com.govind.bookshop.author.domain.dto.AuthorDto}
 * for external representation.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
@Table(name = "authors")
public class AuthorEntity {

    /** Primary key generated by the database (AUTO_INCREMENT / IDENTITY). */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Author name. */
    private String name;

    /** Author age. */
    private Integer age;
}